### ISSUE TITLE
Unable to generate :(

### ISSUE THREAD

**Issue by lgcambero** [enigma0x3/Generate-Macro#12]
I have the following error when generating:

![1](https://cloud.githubusercontent.com/assets/11602705/13272960/c07d4fc8-da7e-11e5-9157-ab63ba16bb43.jpg)
![2](https://cloud.githubusercontent.com/assets/11602705/13272992/0914565a-da7f-11e5-9180-f293b4d47eb3.jpg)

Using Windows 7 Professional 32-bit Office 2013 and PowerShell 2.0 ... probably why ??

**Comment by enigma0x3** [comment]
Are you able to test this on 2010? If not, Ill test this on 2013 and see if I can reproduce it.
