### ISSUE TITLE
stucked at begining

### ISSUE THREAD

**Issue by bgxdoc** [enigma0x3/Generate-Macro#15]
PS C:\users\vm7\desktop> .\Generate-Macro.ps1
File C:\users\vm7\desktop\Generate-Macro.ps1 cannot
em. Please see "get-help about_signing" for more de
At line:1 char:21
+ .\Generate-Macro.ps1 <<<<
    + CategoryInfo          : NotSpecified: (:) [],
    + FullyQualifiedErrorId : RuntimeException

**Comment by ghost** [comment]
Run powershell as admin and type Set-ExecutionPolicy RemoteSigned. Then execute Generate-Macro
