### ISSUE TITLE
Work on kali?

### ISSUE THREAD

**Issue by iNoSec** [enigma0x3/Generate-Macro#18]
i try to work your script on kali but doesnt work, i have this message : 
./Generate-Macro.ps1: ligne 2: erreur de syntaxe près du symbole inattendu « newline »
./Generate-Macro.ps1: ligne 2: `<#'

i delete all comment before the script thats still not work... im so sad man

Thx for helping

**Comment by mattifestation** [comment]
LOL

**Comment by enigma0x3** [comment]
This is a powershell script. Run it on windows.
