### ISSUE TITLE
Task Scheduler name issues

### ISSUE THREAD

**Issue by anirudhrata** [enigma0x3/Generate-Macro#7]
Hi, there seems to be some limitations in Task Scheduler. The task name cannot include a space or it'll fail silently. It'll be good if it is specified in the help. Also the /TR value cannot be greater than 261 characters it seems. So the URL should not be too long.

Can this be made to generate Word documents also?
Awesome work btw.
Thanks.

**Comment by enigma0x3** [comment]
That is one limitation with the scheduled tasks. If you run into a situation where the URL is too long, you can either use a URL shortener or use another persistence method.

Thanks
