### ISSUE TITLE
Unable to generate 

### ISSUE THREAD

**Issue by ghost** [enigma0x3/Generate-Macro#9]
I have the following error when I hit enter to generate :

<pre> <code> Impossible to define the property DisplayAlerts from the Application class.
At C:\Users\user\Desktop\Generate-Macro.ps1:142 : 1
+ $Excel01.DisplayAlerts = "wdAlertsNone"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException

Add-Type : Impossible to load the file or assembly 'Microsoft.Office.Interop.Excel, Version=12.0.0.0,
Culture=neutral, PublicKeyToken=XXXXXXXXXXXXXX' ou une de ses dépendances. The file is not found.
At C:\Users\user\Desktop\Generate-Macro.ps1:154 : 1
+ Add-Type -AssemblyName Microsoft.Office.Interop.Excel
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand

Type [Microsoft.Office.Interop.Excel.XlFileFormat] not found.
At C:\Users\user\Desktop\Generate-Macro.ps1:155 : 1
+ $Workbook01.SaveAs("$global:FullName", [Microsoft.Office.Interop.Exce...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (Microsoft.Offic...el.XlFileFormat:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Saved to file C:\Users\user\Desktop\test2.xls
New-Item : The file 'C:\Users\user\Desktop\RegistryCleanup.ps1' does not exist.
At C:\Users\user\Desktop\Generate-Macro.ps1:170 : 1
+ New-Item $env:userprofile\Desktop\RegistryCleanup.ps1 -type file | Ou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\user\D...stryCleanup.ps1:String) [New-Item], IOException
    + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand

Clean-up Script located at C:\Users\user\Desktop\RegistryCleanup.ps1
</code></pre>

Also, a RegistryCleanup.ps1 powershell script appears on my desktop instead of a .xls file.

I have choose a meterpreter https with logon persistence.

Note : - The error log above is a translation : it can explain some weird sentences.
- I change my public key token to 'XXXXXXXXXX' 
- I use windows 10

**Comment by enigma0x3** [comment]
The script isn't supported on Windows 10. Please use windows 7/8 and office 2010/2013
